Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2021-05, with the labels that each got.

#673 Small UI Tweaks
  Intersect.Client.Framework/File Management/GameContentManager.cs
  Intersect.Client.Framework/Gwen/Control/Base.cs
  Intersect.Client.Framework/Gwen/Control/Menu.cs
  Intersect.Client/Interface/Game/Chat/Chatbox.cs
Labels: bug, enhancement, performance

#706 Update README.md
  README.md
Labels: chore

#726 Add item bankable checks to the second TryDeposit method
  Intersect.Server/Entities/BankInterface.cs
Labels: bug
