Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2022-03, with the labels that each got.

#1089 Fixes a visual glitch when moving elements within the hotbars.
  Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
Labels: bug

#1050 Store and Load the last map Id the editor has worked on when restarting
  Intersect.Editor/Forms/DockingElements/frmMapEditor.cs
  Intersect.Editor/Forms/DockingElements/frmMapList.cs
  Intersect.Editor/Forms/frmMain.cs
  Intersect.Editor/Maps/MapGrid.cs
  Intersect.Editor/Networking/PacketHandler.cs
Labels: enhancement

#1091 Fixes a visual glitch when moving spells within the spells window.
  Intersect.Client/Interface/Game/Spells/SpellsWindow.cs
Labels: bug

#1096 Chore: fixes 'wobbly' targetbox texture when entities move
  Intersect.Client/Entities/Entity.cs
Labels: enhancement, chore

#1044 [MainMenu] Adds Animated Background & DisplayMode Settings.
  Intersect (Core)/Configuration/ClientConfiguration.cs
  Intersect (Core)/Enums/DisplayModes.cs
  Intersect (Core)/Intersect (Core).csproj
  Intersect.Client/Core/Graphics.cs
Labels: feature request

#1019 Modify Asset Packing to pack by file size per batch rather than file count
  Intersect (Core)/Compression/AssetPacker.cs
  Intersect.Editor/Forms/frmMain.cs
  Intersect.Editor/Forms/frmOptions.Designer.cs
  Intersect.Editor/Forms/frmOptions.cs
  Intersect.Editor/Localization/Strings.cs
Labels: enhancement

#1099 FIX: 1087 (Step backward/forward do not work)
  Intersect.Server/Entities/Entity.cs
Labels: bug

#1098 Fix: removes hardcoded ComboBox sound effects
  Intersect.Client.Framework/Gwen/Control/ComboBox.cs
Labels: bug

#968 [Adds Game Settings] Overhead Information.
  Intersect.Client.Framework/Database/GameDatabase.cs
  Intersect.Client/Core/Graphics.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Client/Interface/Shared/SettingsWindow.cs
  Intersect.Client/Localization/Strings.cs
Labels: enhancement, feature request

#961 Position Menu items inside the canvas on Open()
  Intersect.Client.Framework/Gwen/Control/Menu.cs
Labels: bug, chore

#973 Chore: clean up CanCastSpell on Entity and Player.
  Intersect (Core)/Enums/SpellCastFailureReason.cs
  Intersect (Core)/Intersect (Core).csproj
  Intersect.Server/Entities/Entity.cs
  Intersect.Server/Entities/Npc.cs
  Intersect.Server/Entities/Player.cs
  Intersect.Server/Localization/Strings.cs
Labels: bug, chore

#974 Actually interrupt all entity types upon applying an interrupt status, not just players.
  Intersect.Server/Entities/Combat/Status.cs
Labels: bug

#977 Don't allow a reset radius to be set over the maximum value the pathfinder accepts.
  Intersect.Editor/Forms/Editors/frmNpc.cs
  Intersect.Server/Entities/Npc.cs
Labels: bug

#980 Don't allow selection of Move Route target when editing current event move route
  Intersect.Editor/Forms/Editors/Events/Event Commands/Event_MoveRouteDesigner.cs
  Intersect.Editor/Forms/Editors/Events/frmEvent.cs
Labels: bug

#1048 Change Numerical Input field values back-end storage to Double type
  Intersect.Client.Framework/Gwen/Control/NumericUpDown.cs
  Intersect.Client.Framework/Gwen/Control/Slider.cs
  Intersect.Client.Framework/Gwen/Control/TextBoxNumeric.cs
Labels: bug

#1081 Admin Actions: Improves Feedback and Authority checks
  Intersect.Server/Admin/Actions/ActionProcessing.cs
  Intersect.Server/Core/Commands/UnbanCommand.cs
  Intersect.Server/Core/Commands/UnmuteCommand.cs
  Intersect.Server/Database/Logging/Entities/UserActivityHistory.cs
  Intersect.Server/Database/PlayerData/Security/UserRights.cs
  Intersect.Server/Localization/Strings.cs
  Intersect.Server/Networking/PacketHandler.cs
  Intersect.Server/Web/RestApi/Routes/V1/PlayerController.cs
  Intersect.Server/Web/RestApi/Routes/V1/UserController.cs
Labels: bug, enhancement

#1125 fix: go back to using the default output paths
  Directory.build.props
  Intersect.props
Labels: chore

#1033 Ability to arbitrarily change a server variable via command line of server exe
  Intersect.Server/Core/Commands/ApiGrantCommand.cs
  Intersect.Server/Core/Commands/SetVariableCommand.cs
  Intersect.Server/Core/ConsoleService.ConsoleThread.cs
  Intersect.Server/Localization/CommandsNamespace.cs
  Intersect.Server/Localization/Strings.cs
Labels: feature request

#985 Add option to disable lighting effects for slower hardware
  Intersect.Client.Framework/Database/GameDatabase.cs
  Intersect.Client/Core/Graphics.cs
  Intersect.Client/Interface/Shared/SettingsWindow.cs
  Intersect.Client/Localization/Strings.cs
Labels: feature request, performance

#959 Chore: GUI QOL
  Intersect (Core)/Config/PlayerOptions.cs
  Intersect (Core)/Configuration/ClientConfiguration.cs
  Intersect (Core)/CustomColors.cs
  Intersect (Core)/Network/Packets/Client/DepositItemPacket.cs
  Intersect (Core)/Network/Packets/Client/PartyInvitePacket.cs
  Intersect (Core)/Network/Packets/Client/WithdrawItemPacket.cs
  Intersect.Client.Framework/Database/GameDatabase.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Client/Interface/Game/Bag/BagItem.cs
  Intersect.Client/Interface/Game/Bag/BagWindow.cs
  Intersect.Client/Interface/Game/Bank/BankItem.cs
  Intersect.Client/Interface/Game/Bank/BankWindow.cs
  Intersect.Client/Interface/Game/Character/EquipmentItem.cs
  Intersect.Client/Interface/Game/Chat/Chatbox.cs
  Intersect.Client/Interface/Game/GameInterface.cs
  Intersect.Client/Interface/Game/GuildWindow.cs
  Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
  Intersect.Client/Interface/Game/InputBox.cs
  Intersect.Client/Interface/Game/Inventory/InventoryItem.cs
  Intersect.Client/Interface/Game/Inventory/InventoryWindow.cs
  Intersect.Client/Interface/Game/Shop/ShopItem.cs
  Intersect.Client/Interface/Game/Shop/ShopWindow.cs
  Intersect.Client/Interface/Game/Spells/SpellItem.cs
  Intersect.Client/Interface/Game/Spells/SpellsWindow.cs
  Intersect.Client/Interface/Game/Trades/TradeItem.cs
  Intersect.Client/Interface/Game/Trades/TradingWindow.cs
  Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
  Intersect.Client/Interface/Shared/Errors/ErrorWindow.cs
  Intersect.Client/Localization/Strings.cs
  Intersect.Client/Networking/PacketHandler.cs
  Intersect.Client/Networking/PacketSender.cs
  Intersect.Server/Entities/BankInterface.cs
  Intersect.Server/Entities/Player.cs
  Intersect.Server/Localization/Strings.cs
  Intersect.Server/Networking/PacketHandler.cs
  Intersect.Server/Networking/PacketSender.cs
  Intersect.Server/Web/RestApi/Routes/V1/PlayerController.cs
Labels: enhancement, chore

#979 Add Party and Guild to AddChatBoxText event
  Intersect (Core)/Enums/ChatboxChannel.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server/Entities/Events/CommandProcessing.cs
Labels: enhancement

#989 Forcibly reset Npcs on a map once we stop processing it
  Intersect.Server/Core/LogicService.LogicThread.cs
  Intersect.Server/Entities/Entity.cs
  Intersect.Server/Entities/Npc.cs
  Intersect.Server/Maps/MapInstance.cs
Labels: bug

#1006 Adds configurable custom colour for chat bubble text's outline.
  Intersect (Core)/CustomColors.cs
  Intersect.Client/Entities/ChatBubble.cs
Labels: enhancement

#1011 Correctly link new quest task completion events and restore old ones
  Intersect.Editor/Forms/Editors/Quest/frmQuest.cs
  Intersect.Server/Database/GameData/GameContext.cs
  Intersect.Server/Database/GameData/Migrations/FixQuestTaskCompletionEventsMigration.cs
  Intersect.Server/Migrations/Game/20211031200145_FixQuestTaskCompletionEvents.Designer.cs
  Intersect.Server/Migrations/Game/20211031200145_FixQuestTaskCompletionEvents.cs
  Intersect.Server/Networking/PacketHandler.cs
Labels: bug

#1143 Fix 1142
  Intersect.Server/Networking/PacketHandler.cs
Labels: bug

#1147 Adds missing Semicolon at Server/Entities/Player
  Intersect.Server/Entities/Player.cs
Labels: chore

#1139 feat: gui layout hot reloading prototype (#1136)
  Intersect.Client.Framework/Content/ContentWatcher.cs
  Intersect.Client.Framework/File Management/GameContentManager.cs
  Intersect.Client.Framework/Gwen/Control/Base.cs
  Intersect.Client/MonoGame/File Management/MonoContentManager.cs
Labels: feature request

#1149 chore: cleanup package refs
  Intersect (Core)/Intersect.Core.csproj
  Intersect.Client.Framework/Intersect.Client.Framework.csproj
  Intersect.Client/Intersect.Client.csproj
  Intersect.Network/Intersect.Network.csproj
  Intersect.Server/Intersect.Server.csproj
  Intersect.props
Labels: chore

#1016 Add support for Modifiers on hotkeys.
  Intersect.Client/Core/Controls/ControlMap.cs
  Intersect.Client/Core/Controls/ControlValue.cs
  Intersect.Client/Core/Controls/Controls.cs
  Intersect.Client/Core/Input.cs
  Intersect.Client/Interface/Game/Chat/Chatbox.cs
  Intersect.Client/Interface/Game/Hotbar/HotBar.cs
  Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
  Intersect.Client/Interface/Shared/SettingsWindow.cs
  Intersect.Client/MonoGame/Input/MonoInput.cs
Labels: enhancement

#955 Upgraded friendlist
  Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
  Intersect.Client/Interface/Game/Friends/FriendsRow.cs
  Intersect.Client/Interface/Game/Friends/FriendsWindow.cs
  Intersect.Client/Interface/Game/FriendsWindow.cs
  Intersect.Client/Interface/Game/Menu.cs
  Intersect.Client/Localization/Strings.cs
  Intersect.Client/Networking/PacketHandler.cs
Labels: enhancement

#1115 RESOLVE 1045 - Refactor to support Map Instancing
  Intersect (Core)/Config/MapOptions.cs
  Intersect (Core)/GameObjects/Maps/MapBase.cs
  Intersect (Core)/Network/Packets/Server/MapInstanceChangedPacket.cs
  Intersect (Core)/Network/Packets/Server/PlayerEntityPacket.cs
  Intersect.Client/Maps/MapInstance.cs
  Intersect.Client/Networking/PacketHandler.cs
  Intersect.Editor/Maps/MapInstance.cs
  Intersect.Server/Core/LogicService.LogicThread.cs
  Intersect.Server/Database/DbInterface.cs
  Intersect.Server/Database/GameData/GameContext.cs
  Intersect.Server/Database/GameData/IGameContext.cs
  Intersect.Server/Entities/Entity.cs
  Intersect.Server/Entities/Events/CommandProcessing.cs
  Intersect.Server/Entities/Events/Conditions.cs
  Intersect.Server/Entities/Events/Event.cs
  Intersect.Server/Entities/Events/EventPageInstance.cs
  Intersect.Server/Entities/Npc.cs
  Intersect.Server/Entities/Pathfinding/Pathfinder.cs
  Intersect.Server/Entities/Player.cs
  Intersect.Server/Entities/Projectile.cs
  Intersect.Server/Entities/ProjectileSpawn.cs
  Intersect.Server/Entities/Resource.cs
  Intersect.Server/General/Globals.cs
  Intersect.Server/Maps/MapController.cs
  Intersect.Server/Maps/MapGrid.cs
  Intersect.Server/Maps/MapInstance.cs
  Intersect.Server/Maps/MapTrapInstance.cs
  Intersect.Server/Maps/TileHelper.cs
  Intersect.Server/Networking/PacketHandler.cs
  Intersect.Server/Networking/PacketSender.cs
Labels: enhancement, feature request, chore

#1155 feat: UI and debugger improvements
  Intersect (Core)/Async/AsyncValueGenerator`1.cs
  Intersect (Core)/Async/CancellableGenerator`1.cs
  Intersect (Core)/Extensions/EnumerableExtensions.cs
  Intersect (Core)/Localization/LocaleDictionary.cs
  Intersect (Core)/Point.cs
  Intersect.Client.Framework/File Management/GameContentManager.cs
  Intersect.Client.Framework/GenericClasses/Rectangle.cs
  Intersect.Client.Framework/Graphics/GameFont.cs
  Intersect.Client.Framework/Gwen/Control/Base.cs
  Intersect.Client.Framework/Gwen/Control/Data/ITableCellDataProvider.cs
  Intersect.Client.Framework/Gwen/Control/Data/ITableDataProvider.cs
  Intersect.Client.Framework/Gwen/Control/Data/ITableRowDataProvider.cs
  Intersect.Client.Framework/Gwen/Control/Data/ValueTableCellDataProvider`1.cs
  Intersect.Client.Framework/Gwen/Control/IColorableText.cs
  Intersect.Client.Framework/Gwen/Control/ILabel.cs
  Intersect.Client.Framework/Gwen/Control/Label.cs
  Intersect.Client.Framework/Gwen/Control/Layout/Table.cs
  Intersect.Client.Framework/Gwen/Control/Layout/TableRow.cs
  Intersect.Client.Framework/Gwen/Control/ListBox.cs
  Intersect.Client.Framework/Gwen/Control/ListBoxRow.cs
  Intersect.Client.Framework/Gwen/Control/WindowControl.cs
  Intersect.Client.Framework/Gwen/Renderer/IntersectRenderer.cs
  Intersect.Client.Framework/Gwen/Skin/Intersect2021.cs
  Intersect.Client.Framework/Gwen/Skin/TexturedBase.cs
  Intersect.Client/Core/Input.cs
  Intersect.Client/Interface/Debugging/DebugWindow.cs
  Intersect.Client/Interface/Game/DebugMenu.cs
  Intersect.Client/Interface/Game/GameInterface.cs
  Intersect.Client/Interface/Interface.cs
  Intersect.Client/Interface/MutableInterface.cs
  Intersect.Client/Localization/Strings.cs
  Intersect.Client/MonoGame/Audio/MonoMusicSource.cs
Labels: enhancement

#1159 Adding myself as a contributor (#1158)
  AUTHORS.md
Labels: chore

#975 Chore: Clean up equipment bonus effects, they all do the same thing copy/pasted
  Intersect.Server/Entities/Combat/Status.cs
  Intersect.Server/Entities/Entity.cs
  Intersect.Server/Entities/Player.cs
Labels: chore

#1168 Remove inconsistent checks and conversions for lowercase keys in Client Strings
  Intersect.Client/Localization/Strings.cs
Labels: bug

#970 Revamp Item and Spell description windows
  Intersect.Client/Entities/Player.cs
  Intersect.Client/Interface/Game/Bag/BagItem.cs
  Intersect.Client/Interface/Game/Bank/BankItem.cs
  Intersect.Client/Interface/Game/Character/EquipmentItem.cs
  Intersect.Client/Interface/Game/Crafting/RecipeItem.cs
  Intersect.Client/Interface/Game/DescriptionWindows/Components/ComponentBase.cs
  Intersect.Client/Interface/Game/DescriptionWindows/Components/DescriptionComponent.cs
  Intersect.Client/Interface/Game/DescriptionWindows/Components/DividerComponent.cs
  Intersect.Client/Interface/Game/DescriptionWindows/Components/HeaderComponent.cs
  Intersect.Client/Interface/Game/DescriptionWindows/Components/RowContainerComponent.cs
  Intersect.Client/Interface/Game/DescriptionWindows/DescriptionWindowBase.cs
  Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
  Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs
  Intersect.Client/Interface/Game/EntityPanel/SpellStatus.cs
  Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
  Intersect.Client/Interface/Game/Inventory/InventoryItem.cs
  Intersect.Client/Interface/Game/ItemDescWindow.cs
  Intersect.Client/Interface/Game/MapItem/MapItemIcon.cs
  Intersect.Client/Interface/Game/Shop/ShopItem.cs
  Intersect.Client/Interface/Game/SpellDescWindow.cs
  Intersect.Client/Interface/Game/Spells/SpellItem.cs
  Intersect.Client/Interface/Game/Trades/TradeItem.cs
  Intersect.Client/Localization/Strings.cs
Labels: enhancement
