Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2022-04, with the labels that each got.

#1184 fix: removes unnecessary check in LogicService.LogicThread.cs
  Intersect.Server/Core/LogicService.LogicThread.cs
Labels: bug, chore

#1175 Fix 1174
  Intersect (Core)/Config/BankOptions.cs
  Intersect (Core)/Config/Guilds/GuildOptions.cs
  Intersect (Core)/Config/Options.cs
  Intersect (Core)/Config/PlayerOptions.cs
  Intersect (Core)/Intersect (Core).csproj
  Intersect.Client/Interface/Game/Bank/BankWindow.cs
  Intersect.Server/Database/PlayerData/Migrations/GuildBankMaxSlotMigration.cs
  Intersect.Server/Database/PlayerData/PlayerContext.cs
  Intersect.Server/Database/PlayerData/Players/Guild.cs
  Intersect.Server/Entities/Player.cs
  Intersect.Server/Intersect.Server.csproj
  Intersect.Server/Migrations/20220331140427_GuildBankMaxSlotsMigration.Designer.cs
  Intersect.Server/Migrations/20220331140427_GuildBankMaxSlotsMigration.cs
Labels: bug

#1211 fix: rewrite text insertion/replacement logic
  Intersect.Client.Framework/Gwen/Control/TextBox.cs
Labels: bug

#1212 chore: Moves 'Auto-close Windows' to Game Settings
  Intersect.Client/Interface/Shared/SettingsWindow.cs
  Intersect.Client/Localization/Strings.cs
Labels: chore

#1223 fix: avoid RemoveAll
  Intersect.Client.Framework/Content/ContentWatcher.cs
Labels: bug
