Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2023-08, with the labels that each got.

#1835 avoid description window to delete control twice
  Intersect.Client/Interface/Game/DescriptionWindows/Components/ComponentBase.cs
Labels: help wanted

#1849 fix #1848 - map events not being deleted when the parent maps are removed
  Intersect.Server/Database/DbInterface.cs
  Intersect.Server/Networking/PacketHandler.cs
Labels: help wanted

#1837 fix: prevent crashing when stopping active crafting
  Intersect.Server/Entities/Player.cs
  Intersect.Server/Networking/PacketHandler.cs
Labels: help wanted

#1855 Allow firing projectiles while facing events whos trigger is not 'Action Button'
  Intersect (Core)/Network/Packets/Server/EventEntityPacket.cs
  Intersect.Client/Entities/Events/Event.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Server/Entities/Events/EventPageInstance.cs
Labels: help wanted

#1797 feat: map editor cursor sprites
  Intersect.Editor/Configuration/ToolCursor.cs
  Intersect.Editor/Core/Database.cs
  Intersect.Editor/Core/Graphics.cs
  Intersect.Editor/Forms/DockingElements/frmMapEditor.Designer.cs
  Intersect.Editor/Forms/DockingElements/frmMapEditor.cs
  Intersect.Editor/Forms/DockingElements/frmMapList.cs
  Intersect.Editor/Forms/frmMain.Designer.cs
  Intersect.Editor/Forms/frmMain.cs
  Intersect.Editor/Forms/frmMain.resx
  Intersect.Editor/Forms/frmOptions.Designer.cs
  Intersect.Editor/Forms/frmOptions.cs
  Intersect.Editor/General/Enums.cs
  Intersect.Editor/General/Globals.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Editor/Maps/MapGrid.cs
  Intersect.Editor/Properties/Resources.Designer.cs
  Intersect.Editor/Properties/Resources.resx
  Intersect.Editor/Resources/paintbrush.png
Labels: enhancement, feature request

#1886 fix: (Day) 1885 - Issue where custom cursors didn't work with zoom
  Intersect.Client/Core/Graphics.cs
Labels: bug

#1888 fix: (Day) 1887 - Fixes issues with zoom out at >32px tile size
  Intersect.Client/Core/Graphics.cs
  Intersect.Client/Entities/Resource.cs
Labels: bug
