Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2023-11, with the labels that each got.

#2007 fix: safe checks on fog displacement
  Intersect.Client/Maps/MapInstance.cs
Labels: bug

#2073 feat: (Day) Adds custom player name colors for in-party/in-guild/hostile
  Intersect (Core)/CustomColors.cs
  Intersect.Client.Framework/Maps/IMapInstance.cs
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/Player.cs
Labels: enhancement

#2075 feat: (Day) Add ability to enable self-cast when casting friendly spe…
  Intersect (Core)/Config/CombatOptions.cs
  Intersect.Server.Core/Entities/Entity.cs
Labels: enhancement

#2077 feat: (Day) Add ability to run common event for all players on an ins…
  Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs
  Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_StartCommonEvent.Designer.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_StartCommonEvent.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
Labels: enhancement

#2079 feat: (Day) Allows animations to be instanced to their player n event…
  Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs
  Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_PlayAnimation.Designer.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_PlayAnimation.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
  Intersect.Server.Core/Networking/PacketSender.cs
Labels: enhancement

#2082 fix: (Day) Fix issue with bags not being saved properly
  Intersect.Server.Core/Entities/Player.cs
Labels: bug

#2071 feat: (Day) Add option to allow safe zones to consider any player friendly
  Intersect (Core)/Config/CombatOptions.cs
  Intersect.Server.Core/Entities/Player.cs
Labels: enhancement

#2093 feat: (Day) Add an instance controller for prep for future work
  Intersect.Server.Core/Core/LogicService.LogicThread.cs
  Intersect.Server.Core/Core/MapInstancing/Controllers/InstanceController.cs
  Intersect.Server.Core/Core/MapInstancing/InstanceProcessor.cs
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
  Intersect.Server.Core/Entities/Player.cs
  Intersect.Server.Core/Maps/MapController.cs
  Intersect.Server.Core/Maps/MapInstance.cs
Labels: enhancement

#2092 feat: (Day) Add FadeIn/FadeOut event commands
  Intersect (Core)/Configuration/ClientConfiguration.cs
  Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs
  Intersect (Core)/GameObjects/Events/Enums.cs
  Intersect (Core)/Network/Packets/Client/FadeCompletePacket.cs
  Intersect (Core)/Network/Packets/Server/FadePacket.cs
  Intersect.Client/Core/Fade.cs
  Intersect.Client/Core/Graphics.cs
  Intersect.Client/Core/Input.cs
  Intersect.Client/Core/Main.cs
  Intersect.Client/Networking/PacketHandler.cs
  Intersect.Client/Networking/PacketSender.cs
  Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeItems.Designer.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeItems.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ScreenFade.Designer.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ScreenFade.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ScreenFade.resx
  Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs
  Intersect.Editor/Forms/Editors/Events/frmEvent.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server.Core/Entities/Events/CommandInstance.cs
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
  Intersect.Server.Core/Entities/Events/Event.cs
  Intersect.Server.Core/Entities/Player.cs
  Intersect.Server.Core/Networking/PacketHandler.cs
  Intersect.Server.Core/Networking/PacketSender.cs
Labels: feature request

#2097 feature/chore: format for abbreviated time
  Intersect (Core)/Intersect.Core.csproj
  Intersect (Core)/Utilities/MeasurementExtensions.cs
  Intersect (Core)/Utilities/MeasurementFormattingResources.Designer.cs
  Intersect (Core)/Utilities/MeasurementFormattingResources.resx
  Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
  Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs
  Intersect.Client/Interface/Game/EntityPanel/SpellStatus.cs
  Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
  Intersect.Client/Interface/Game/Inventory/InventoryItem.cs
  Intersect.Client/Interface/Game/Spells/SpellItem.cs
  Intersect.Client/Localization/Strings.cs
Labels: enhancement, feature request, chore

#1851 fix: (Day) 1850 - Fix issue where you could kick players from an inst…
  Intersect (Core)/Config/InstancingOptions.cs
  Intersect.Server.Core/Entities/Player.cs
  Intersect.Server.Core/Localization/Strings.cs
  Intersect.sln
Labels: bug

#2124 fix: (Day) Fix so enemies can cast friendly spells on eachother
  Intersect.Server.Core/Entities/Npc.cs
Labels: bug
