Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2023-03, with the labels that each got.

#1732 enhancement: admin window
  Intersect.Client.Framework/Gwen/Control/TreeNode.cs
  Intersect.Client/Interface/Game/AdminWindow.cs
  Intersect.Client/Interface/Game/BanMuteBox.cs
  Intersect.Client/Localization/Strings.cs
Labels: enhancement

#1719 enhancement: directly compare with TimeSystem conditions
  Intersect (Core)/GameObjects/Events/Condition.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.Designer.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server/Entities/Events/CommandProcessing.cs
  Intersect.Server/Entities/Events/Conditions.cs
  Intersect.Server/Entities/Events/VariableCheckHandlerRegistry.cs
Labels: enhancement

#1707 chore: overhead hp bar
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/Player.cs
Labels: chore

#1738 feat: (Day) Typewriter Text
  Intersect (Core)/Configuration/ClientConfiguration.cs
  Intersect (Core)/Enums/TypewriterBehavior.cs
  Intersect (Core)/GameObjects/Events/Enums.cs
  Intersect.Client.Framework/Database/GameDatabase.cs
  Intersect.Client.Framework/Gwen/Control/RichLabel.cs
  Intersect.Client/Core/Audio.cs
  Intersect.Client/Core/Sounds/Sound.cs
  Intersect.Client/Interface/Game/EventWindow.cs
  Intersect.Client/Interface/Game/Typewriting/Typewriter.cs
  Intersect.Client/Interface/Shared/SettingsWindow.cs
  Intersect.Client/Localization/Strings.cs
Labels: enhancement, feature request

#1746 chore and fix: typewriter
  Intersect.Client/Interface/Game/Typewriting/Typewriter.cs
Labels: chore

#1701 chore: overhead name rendering
  Intersect.Client/Core/Graphics.cs
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/Player.cs
Labels: chore

#1674 enhancements and fixes: attack, block and cast animations
  Intersect (Core)/Config/SpriteOptions.cs
  Intersect.Client/Core/Input.cs
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Server/Entities/Entity.cs
  Intersect.Server/Entities/Npc.cs
  Intersect.Server/Networking/PacketHandler.cs
Labels: enhancement, chore

#1748 chore: enum corrective naming
  Intersect (Core)/Enums/ItemEffect.cs
  Intersect (Core)/Enums/SpellEffect.cs
  Intersect (Core)/GameObjects/ItemBase.cs
  Intersect (Core)/GameObjects/NpcBase.cs
  Intersect (Core)/GameObjects/SpellBase.cs
  Intersect (Core)/Network/Packets/Server/StatusPacket.cs
  Intersect.Client.Framework/Entities/IStatus.cs
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Client/Entities/Status.cs
  Intersect.Client/Interface/Game/Character/CharacterWindow.cs
  Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
  Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs
  Intersect.Client/Networking/PacketHandler.cs
  Intersect.Editor/Forms/Editors/frmItem.cs
  Intersect.Editor/Forms/Editors/frmNpc.cs
  Intersect.Editor/Forms/Editors/frmSpell.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server/Entities/Combat/DoT.cs
  Intersect.Server/Entities/Combat/Status.cs
  Intersect.Server/Entities/Entity.cs
  Intersect.Server/Entities/Npc.cs
  Intersect.Server/Entities/Player.cs
  Intersect.Server/Maps/MapInstance.cs
  Intersect.Server/Networking/PacketHandler.cs
Labels: chore

#1756 chore: paperdollDir
  Intersect.Client/Entities/Entity.cs
Labels: chore

#1772 chore: AccessLevel and NpcAggression
  Intersect (Core)/Enums/NpcAggression.cs
  Intersect (Core)/Enums/NpcBehavior.cs
  Intersect (Core)/Network/Packets/Server/NpcAggressionPacket.cs
  Intersect (Core)/Network/Packets/Server/NpcEntityPacket.cs
  Intersect (Core)/Network/Packets/Server/PlayerEntityPacket.cs
  Intersect.Client.Framework/Entities/IEntity.cs
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Server/Entities/Npc.cs
  Intersect.Server/Entities/Player.cs
Labels: chore
