Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2023-09, with the labels that each got.

#1894 fix: (Day) Fix issue where emails were not used when searching for a …
  Intersect.Server/Database/PlayerData/User.cs
Labels: bug

#1896 fix: Game DB migration to MySQL
  Intersect.Server/Migrations/Game/20201001163344_ItemAndSpellCooldownImprovements.cs
  Intersect.Server/Migrations/Game/20211026130945_NpcImmunityMigration.cs
Labels: bug

#1895 fix: projectile diagonal directions
  Intersect (Core)/GameObjects/ProjectileBase.cs
Labels: bug

#1899 fix: entityExperienceToNextLevel as Long within EntityBox
  Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Labels: bug

#1900 fix/enhancement: remove bounded spells through events
  Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeSpells.Designer.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeSpells.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server/Entities/Events/CommandProcessing.cs
  Intersect.Server/Entities/Player.cs
Labels: bug, enhancement

#1901 fix: cast entityExperience to float for percentage calculation
  Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Labels: bug

#1832 fix: correctly removes currency amount inShop
  Intersect.Server/Entities/Player.cs
  Intersect.Server/Localization/Strings.cs
Labels: help wanted, chore
