Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2024-06, with the labels that each got.

#2265 fix: equipment dont showing stat info on crafting
  Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
Labels: bug fix

#2266 fix: add more equip checks for more conditions
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
  Intersect.Server.Core/Entities/Player.cs
  Intersect.Server.Core/Networking/PacketHandler.cs
Labels: bug fix

#2264 fix: editor crashes on specifics variable mods
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_Variable.cs
Labels: bug fix

#2267 fix: player infinite blocking state on client side
  Intersect.Client/Entities/Player.cs
Labels: bug fix

#2278 fix: adds missing projectile grid size checks
  Intersect.Client/Entities/Projectiles/Projectile.cs
  Intersect.Server.Core/Entities/Projectile.cs
Labels: bug fix

#2281 fix: bugs about projectile system
  Intersect.Client/Entities/Projectiles/Projectile.cs
  Intersect.Server.Core/Entities/Entity.cs
  Intersect.Server.Core/Entities/Projectile.cs
Labels: bug fix

#2277 enhancement: player, target and status window revamp
  Intersect.Client.Framework/Gwen/Control/Base.cs
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Client/Interface/Game/DescriptionWindows/Components/ComponentBase.cs
  Intersect.Client/Interface/Game/DescriptionWindows/DescriptionWindowBase.cs
  Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs
  Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
  Intersect.Client/Interface/Game/EntityPanel/PlayerStatusWindow.cs
  Intersect.Client/Interface/Game/EntityPanel/SpellStatus.cs
  Intersect.Client/Interface/Game/GameInterface.cs
  Intersect.Client/Localization/Strings.cs
  Intersect.Client/Networking/PacketHandler.cs
Labels: enhancement, chore

#2288 Revert "feature: amount range for item drops"
  Intersect (Core)/GameObjects/Drop.cs
  Intersect.Editor/Forms/Editors/frmNpc.Designer.cs
  Intersect.Editor/Forms/Editors/frmNpc.cs
  Intersect.Editor/Forms/Editors/frmNpc.resx
  Intersect.Editor/Forms/Editors/frmResource.Designer.cs
  Intersect.Editor/Forms/Editors/frmResource.cs
  Intersect.Editor/Forms/Editors/frmResource.resx
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server.Core/Entities/Npc.cs
  Intersect.Server.Core/Entities/Resource.cs
  Intersect.Server.Core/Migrations/Sqlite/Game/20240607220428_RandomDrops.Designer.cs
  Intersect.Server.Core/Migrations/Sqlite/Game/20240607220428_RandomDrops.cs
Labels: bug fix

#2289 enhancement: optional target window
  Intersect (Core)/Config/CombatOptions.cs
  Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Labels: enhancement
