Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2024-07, with the labels that each got.

#2295 projectile refactoring: fixes, docs, enhancements
  Intersect.Client/Entities/Projectiles/Projectile.cs
  Intersect.Client/Entities/Projectiles/ProjectileSpawns.cs
  Intersect.Server.Core/Entities/Projectile.cs
  Intersect.Server.Core/Entities/ProjectileSpawn.cs
Labels: enhancement, chore, performance, bug fix

#2296 fix: player status timer
  Intersect.Client/Interface/Game/EntityPanel/PlayerStatusWindow.cs
Labels: bug fix

#2298 chore: removing unused usings from server core
  Intersect.Server.Core/Core/MapInstancing/Controllers/InstanceController.cs
  Intersect.Server.Core/Core/MapInstancing/InstanceProcessor.cs
  Intersect.Server.Core/Entities/BankInterface.cs
  Intersect.Server.Core/Entities/Combat/Buff.cs
  Intersect.Server.Core/Entities/Combat/Dash.cs
  Intersect.Server.Core/Entities/Combat/DoT.cs
  Intersect.Server.Core/Entities/Combat/Stat.cs
  Intersect.Server.Core/Entities/Combat/Status.cs
  Intersect.Server.Core/Entities/Entity.Comparison.cs
  Intersect.Server.Core/Entities/Events/CommandInstance.cs
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
  Intersect.Server.Core/Entities/Events/ConditionHandlerRegistry.cs
  Intersect.Server.Core/Entities/Events/Conditions.cs
  Intersect.Server.Core/Entities/Events/Event.cs
  Intersect.Server.Core/Entities/Events/EventPageInstance.cs
  Intersect.Server.Core/Entities/Events/VariableCheckHandlerRegistry.cs
  Intersect.Server.Core/Entities/Npc.cs
  Intersect.Server.Core/Entities/Resource.cs
  Intersect.Server.Core/Entities/Trading.cs
  Intersect.Server.Core/General/Formulas.cs
  Intersect.Server.Core/General/Globals.cs
  Intersect.Server.Core/General/Time.cs
  Intersect.Server.Core/Localization/Strings.cs
  Intersect.Server.Core/Maps/MapActionMessages.cs
  Intersect.Server.Core/Maps/MapAnimations.cs
  Intersect.Server.Core/Maps/MapController.cs
  Intersect.Server.Core/Maps/MapEntityMovements.cs
  Intersect.Server.Core/Maps/MapInstance.cs
  Intersect.Server.Core/Maps/MapItemInstance.cs
  Intersect.Server.Core/Maps/MapItemSpawn.cs
  Intersect.Server.Core/Maps/MapTileLoc.cs
  Intersect.Server.Core/Maps/MapTrapInstance.cs
  Intersect.Server.Core/Maps/TileHelper.cs
  Intersect.Server.Core/Networking/PacketHandler.cs
  Intersect.Server.Core/Networking/PacketSender.cs
Labels: chore

#2309 chore: removes unnecessary and implicit usings from intersect network
  Intersect.Network/Lidgren/LidgrenBuffer.cs
  Intersect.Network/Lidgren/LidgrenConnection.cs
  Intersect.Network/Lidgren/LidgrenInterface.cs
  Intersect.Network/LiteNetLib/AesAlgorithm.cs
  Intersect.Network/LiteNetLib/LiteNetLibConnection.cs
Labels: chore

#2315 chore: converts network namespaces to file-scoped namespaces
  Intersect.Network/ClientNetwork.cs
  Intersect.Network/IServer.cs
  Intersect.Network/Lidgren/LidgrenBuffer.cs
  Intersect.Network/Lidgren/LidgrenConnection.cs
  Intersect.Network/Lidgren/LidgrenInterface.cs
  Intersect.Network/NetworkMetaStatus.cs
Labels: chore

#2318 fix: editor build after cleanup
  Intersect.Editor/Content/ContentManager.cs
  Intersect.Editor/Forms/DockingElements/frmMapGrid.cs
  Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
  Intersect.Editor/Forms/DockingElements/frmMapList.cs
  Intersect.Editor/Forms/DockingElements/frmMapProperties.cs
  Intersect.Editor/Forms/Editors/EditorForm.cs
  Intersect.Editor/Forms/Editors/Events/frmEvent.cs
  Intersect.Editor/Forms/Editors/Quest/frmQuest.cs
  Intersect.Editor/Forms/Editors/frmAnimation.cs
  Intersect.Editor/Forms/Editors/frmClass.cs
  Intersect.Editor/Forms/Editors/frmCraftingTables.cs
  Intersect.Editor/Forms/Editors/frmCrafts.cs
  Intersect.Editor/Forms/Editors/frmDynamicRequirements.cs
  Intersect.Editor/Forms/Editors/frmItem.cs
  Intersect.Editor/Forms/Editors/frmNpc.cs
  Intersect.Editor/Forms/Editors/frmProjectile.cs
  Intersect.Editor/Forms/Editors/frmResource.cs
  Intersect.Editor/Forms/Editors/frmShop.cs
  Intersect.Editor/Forms/Editors/frmSpell.cs
  Intersect.Editor/Forms/Editors/frmVariable.cs
  Intersect.Editor/Forms/frmAbout.cs
  Intersect.Editor/Forms/frmMain.cs
  Intersect.Editor/Forms/frmOptions.cs
  Intersect.Editor/Forms/frmProgress.cs
  Intersect.Editor/Forms/frmUpdate.cs
  Intersect.Editor/Forms/frmVariableSelector.cs
  Intersect.Editor/Forms/frmWarpSelection.cs
  Intersect.Editor/Maps/MapGrid.cs
  Intersect.Editor/Maps/MapInstance.cs
  Intersect.Editor/Networking/PacketHandler.cs
Labels: bug fix

#2320 fix: client side projectile issue
  Intersect.Client/Entities/Projectiles/Projectile.cs
Labels: bug fix

#2322 enhancement: bind description window to hovered control
  Intersect (Core)/Intersect.Core.csproj
  Intersect.Client/Interface/Game/DescriptionWindows/DescriptionWindowBase.cs
  Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
  Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs
  Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
Labels: enhancement, bug fix

#2326 chore: client cleanup (core and entities)
  Intersect.Client.Framework/Entities/IAnimation.cs
  Intersect.Client.Framework/Entities/IEntity.cs
  Intersect.Client.Framework/Entities/IFriendInstance.cs
  Intersect.Client.Framework/Entities/IPlayer.cs
  Intersect.Client.Framework/Entities/IResource.cs
  Intersect.Client.Framework/Graphics/GameRenderer.cs
  Intersect.Client/Core/Audio.cs
  Intersect.Client/Core/Bootstrapper.cs
  Intersect.Client/Core/ClientCommandLineOptions.cs
  Intersect.Client/Core/ClientContext.cs
  Intersect.Client/Core/Controls/ControlEnum.cs
  Intersect.Client/Core/Controls/ControlMap.cs
  Intersect.Client/Core/Controls/ControlValue.cs
  Intersect.Client/Core/Controls/Controls.cs
  Intersect.Client/Core/Fade.cs
  Intersect.Client/Core/Graphics.cs
  Intersect.Client/Core/Input.cs
  Intersect.Client/Core/Main.cs
  Intersect.Client/Core/Sounds/MapSound.cs
  Intersect.Client/Core/Sounds/Sound.cs
  Intersect.Client/Entities/Animation.cs
  Intersect.Client/Entities/ChatBubble.cs
  Intersect.Client/Entities/Critter.cs
  Intersect.Client/Entities/Dash.cs
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/Events/Dialog.cs
  Intersect.Client/Entities/Events/Event.cs
  Intersect.Client/Entities/Events/Hold.cs
  Intersect.Client/Entities/FriendInstance.cs
  Intersect.Client/Entities/HotbarInstance.cs
  Intersect.Client/Entities/PartyMember.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Client/Entities/Projectiles/Projectile.cs
  Intersect.Client/Entities/Projectiles/ProjectileSpawns.cs
  Intersect.Client/Entities/Resource.cs
  Intersect.Client/Entities/Status.cs
  Intersect.Client/General/Globals.cs
  Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
  Intersect.Client/Interface/Game/EventWindow.cs
  Intersect.Client/Interface/Game/Friends/FriendsWindow.cs
  Intersect.Client/Interface/Game/InputBox.cs
  Intersect.Client/Interface/Game/MapItem/MapItemIcon.cs
  Intersect.Client/Interface/Game/MapItem/MapItemWindow.cs
  Intersect.Client/MonoGame/Graphics/MonoRenderer.cs
  Intersect.Client/Networking/PacketHandler.cs
Labels: chore

#2328 enhancement: press enter key to select character to play
  Intersect.Client/Core/Input.cs
  Intersect.Client/Interface/Menu/MainMenu.cs
  Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
Labels: enhancement

#2334 fix: entity animation texture
  Intersect.Client/Entities/Entity.cs
Labels: bug fix

#2337 fix: spell item description
  Intersect.Client/Interface/Game/DescriptionWindows/Components/ComponentBase.cs
  Intersect.Client/Interface/Game/DescriptionWindows/DescriptionWindowBase.cs
  Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
  Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs
Labels: bug fix

#2338 chore: server core localized strings
  Intersect.Client/Networking/PacketHandler.cs
  Intersect.Server.Core/Core/Bootstrapper.cs
  Intersect.Server.Core/Core/ServerContext.cs
  Intersect.Server.Core/Database/DbInterface.cs
  Intersect.Server.Core/Database/PlayerData/Ban.cs
  Intersect.Server.Core/Database/PlayerData/Mute.cs
  Intersect.Server.Core/Database/PlayerData/Players/Guild.cs
  Intersect.Server.Core/Database/PlayerData/User.cs
  Intersect.Server.Core/Entities/BankInterface.cs
  Intersect.Server.Core/Entities/Entity.cs
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
  Intersect.Server.Core/Entities/Events/Event.cs
  Intersect.Server.Core/Entities/Player.cs
  Intersect.Server.Core/General/Formulas.cs
  Intersect.Server.Core/Localization/Strings.cs
  Intersect.Server.Core/Networking/PacketHandler.cs
  Intersect.Server.Core/Networking/PacketSender.cs
  Intersect.Server/Admin/Actions/ActionProcessing.cs
  Intersect.Server/Core/Commands/ApiCommand.cs
  Intersect.Server/Core/Commands/ApiGrantCommand.cs
  Intersect.Server/Core/Commands/ApiRevokeCommand.cs
  Intersect.Server/Core/Commands/ApiRolesCommand.cs
  Intersect.Server/Core/Commands/BanCommand.cs
  Intersect.Server/Core/Commands/CpsCommand.cs
  Intersect.Server/Core/Commands/HelpCommand.cs
  Intersect.Server/Core/Commands/KickCommand.cs
  Intersect.Server/Core/Commands/KillCommand.cs
  Intersect.Server/Core/Commands/MetricsCommand.cs
  Intersect.Server/Core/Commands/ModeratorActionCommand.cs
  Intersect.Server/Core/Commands/MuteCommand.cs
  Intersect.Server/Core/Commands/OnlineListCommand.cs
  Intersect.Server/Core/Commands/PowerAccountCommand.cs
  Intersect.Server/Core/Commands/PowerCommand.cs
  Intersect.Server/Core/Commands/UnbanCommand.cs
  Intersect.Server/Core/Commands/UnmuteCommand.cs
  Intersect.Server/Core/ConsoleService.ConsoleThread.cs
  Intersect.Server/Core/FullServerContext.cs
  Intersect.Server/Networking/Helpers/NetDebug.cs
  Intersect.Server/Networking/Helpers/UPnP.cs
  Intersect.Server/Networking/NetworkedPacketHandler.cs
  Intersect.Server/Notifications/Notification.cs
  Intersect.Server/Notifications/ResetPassword.cs
  Intersect.Server/Web/RestApi/Routes/V1/GuildController.cs
  Intersect.Server/Web/RestApi/Routes/V1/PlayerController.cs
  Intersect.Server/Web/RestApi/Routes/V1/UserController.cs
Labels: enhancement, chore, bug fix

#2260 fix: editor NSE for instance type strings
  Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_Warp.cs
  Intersect.Editor/Localization/Strings.cs
Labels: bug fix

#2340 refactor mutable interface
  Intersect.Client.Framework/Interface/IMutableInterface.cs
  Intersect.Client/Interface/MutableInterface.cs
Labels: chore

#2342 feature: display quantity of items within hotbar slots
  Intersect.Client/Interface/Game/Hotbar/HotBar.cs
  Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
Labels: enhancement, feature request

#2343 chore: refactor error window
  Intersect.Client/Interface/Game/InputBox.cs
  Intersect.Client/Interface/Interface.cs
  Intersect.Client/Interface/Shared/ErrorWindow.cs
  Intersect.Client/Interface/Shared/Errors/ErrorHandler.cs
  Intersect.Client/Interface/Shared/Errors/ErrorWindow.cs
Labels: chore

#2344 chore: refactor settings window
  Intersect.Client/Interface/Game/EscapeMenu.cs
  Intersect.Client/Interface/Shared/SettingsWindow.cs
Labels: chore

#2345 chore: refactor create character window
  Intersect.Client.Framework/Gwen/Control/ImagePanel.cs
  Intersect.Client/Interface/Menu/CreateCharacterWindow.cs
Labels: chore

#2351 enhancement: ability to drop multiple stacks of stackable items
  Intersect.Client/Entities/Player.cs
  Intersect.Client/Interface/Game/Inventory/InventoryItem.cs
  Intersect.Client/Interface/Shared/InputBox.cs
Labels: enhancement, bug fix
