Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2024-05, with the labels that each got.

#2239 fix: typo in event command type for setGuildBankSlotsTreeNode
  Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs
Labels: bug

#2247 fix: update ping information
  Intersect.Network/ClientNetwork.cs
Labels: bug

#2250 chore: long value type for Vitals, Exp and ConsumableData
  Intersect (Core)/GameObjects/ClassBase.cs
  Intersect (Core)/GameObjects/ItemBase.cs
  Intersect (Core)/GameObjects/NpcBase.cs
  Intersect (Core)/GameObjects/SpellBase.cs
  Intersect (Core)/Network/Packets/Server/EntityPacket.cs
  Intersect (Core)/Network/Packets/Server/EntityVitalsPacket.cs
  Intersect (Core)/Network/Packets/Server/MapEntityVitalsPacket.cs
  Intersect (Core)/Network/Packets/Server/PartyMemberPacket.cs
  Intersect (Core)/Network/Packets/Server/StatusPacket.cs
  Intersect (Core)/Utilities/DatabaseUtils.cs
  Intersect.Client.Framework/Entities/IEntity.cs
  Intersect.Client.Framework/Entities/IPartyMember.cs
  Intersect.Client.Framework/Entities/IStatus.cs
  Intersect.Client/Entities/Entity.cs
  Intersect.Client/Entities/PartyMember.cs
  Intersect.Client/Entities/Status.cs
  Intersect.Client/Interface/Game/Character/CharacterWindow.cs
  Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
  Intersect.Server.Core/Entities/Combat/Status.cs
  Intersect.Server.Core/Entities/Entity.cs
  Intersect.Server.Core/Entities/Npc.cs
  Intersect.Server.Core/Entities/Player.cs
  Intersect.Server.Core/Entities/Resource.cs
  Intersect.Server.Core/General/Formulas.cs
Labels: enhancement, chore

#2241 fix: set LastAttackingWeapon for EquipmentOnHitTriggers
  Intersect.Server.Core/Entities/Player.cs
Labels: bug

#2246 fix: server crash when crafting
  Intersect.Server.Core/Entities/Player.cs
Labels: bug

#2252 chore: client localized strings
  Intersect.Client/Core/Main.cs
  Intersect.Client/Entities/Player.cs
  Intersect.Client/Interface/Game/AdminWindow.cs
  Intersect.Client/Interface/Game/Bag/BagWindow.cs
  Intersect.Client/Interface/Game/BanMuteBox.cs
  Intersect.Client/Interface/Game/Bank/BankWindow.cs
  Intersect.Client/Interface/Game/Character/CharacterWindow.cs
  Intersect.Client/Interface/Game/Chat/Chatbox.cs
  Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs
  Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
  Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
  Intersect.Client/Interface/Game/EscapeMenu.cs
  Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
  Intersect.Client/Interface/Game/InputBox.cs
  Intersect.Client/Interface/Game/Inventory/InventoryItem.cs
  Intersect.Client/Interface/Game/Menu.cs
  Intersect.Client/Interface/Game/PartyWindow.cs
  Intersect.Client/Interface/Game/QuestOfferWindow.cs
  Intersect.Client/Interface/Game/QuestsWindow.cs
  Intersect.Client/Interface/Game/Shop/ShopItem.cs
  Intersect.Client/Interface/Game/Spells/SpellsWindow.cs
  Intersect.Client/Interface/Game/Trades/TradeSegment.cs
  Intersect.Client/Interface/Game/Trades/TradingWindow.cs
  Intersect.Client/Interface/Menu/CreateCharacterWindow.cs
  Intersect.Client/Interface/Menu/CreditsWindow.cs
  Intersect.Client/Interface/Menu/ForgotPasswordWindow.cs
  Intersect.Client/Interface/Menu/LoginWindow.cs
  Intersect.Client/Interface/Menu/RegisterWindow.cs
  Intersect.Client/Interface/Menu/ResetPasswordWindow.cs
  Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
  Intersect.Client/Interface/Shared/Errors/ErrorHandler.cs
  Intersect.Client/Interface/Shared/SettingsWindow.cs
  Intersect.Client/Localization/Strings.cs
  Intersect.Client/MonoGame/Audio/MonoMusicSource.cs
  Intersect.Client/MonoGame/Audio/MonoSoundSource.cs
  Intersect.Client/MonoGame/File Management/MonoContentManager.cs
  Intersect.Client/MonoGame/Graphics/MonoRenderer.cs
  Intersect.Client/MonoGame/Graphics/MonoTexture.cs
  Intersect.Client/MonoGame/IntersectGame.cs
  Intersect.Client/Networking/Network.cs
  Intersect.Client/Networking/PacketHandler.cs
Labels: chore

#2254 fix: don't clear current target when taunted
  Intersect.Client/Core/Input.cs
Labels: bug fix

#2256 feature: unequip item by slot
  Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs
  Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.Designer.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.resx
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
Labels: enhancement, feature request

#2257 fix: disconnection error message when returning to the main menu
  Intersect (Core)/Network/Packets/Client/LogoutPacket.cs
  Intersect.Client/Core/Main.cs
  Intersect.Client/Interface/Game/EscapeMenu.cs
  Intersect.Client/Interface/Menu/CreateCharacterWindow.cs
  Intersect.Client/Interface/Menu/ForgotPasswordWindow.cs
  Intersect.Client/Interface/Menu/RegisterWindow.cs
  Intersect.Client/Interface/Menu/ResetPasswordWindow.cs
  Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
  Intersect.Client/Networking/PacketSender.cs
  Intersect.Server.Core/Networking/PacketHandler.cs
Labels: bug fix

#2258 fix: disconnection error when returning to main menu
  Intersect (Core)/Network/Packets/Client/LogoutPacket.cs
  Intersect.Client/Core/Main.cs
  Intersect.Client/General/Globals.cs
  Intersect.Client/Interface/Game/EscapeMenu.cs
  Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
  Intersect.Client/Networking/Network.cs
  Intersect.Client/Networking/PacketSender.cs
  Intersect.Server.Core/Networking/PacketHandler.cs
Labels: bug fix
