Repository AscensionGameDev/Intersect-Engine, pull requests merged in 2024-03, with the labels that each got.

#2173 2172: Add support for a crafting journal
  Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs
  Intersect (Core)/Network/Packets/Server/CraftingTablePacket.cs
  Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs
  Intersect.Client/Interface/Game/GameInterface.cs
  Intersect.Client/Networking/PacketHandler.cs
  Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_OpenCrafting.Designer.cs
  Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_OpenCrafting.cs
  Intersect.Editor/Localization/Strings.cs
  Intersect.Server.Core/Entities/Events/CommandProcessing.cs
  Intersect.Server.Core/Entities/Player.cs
  Intersect.Server.Core/Localization/Strings.cs
  Intersect.Server.Core/Networking/PacketHandler.cs
  Intersect.Server.Core/Networking/PacketSender.cs
Labels: enhancement

#2174 fix: last projectile spell casting
  Intersect.Server.Core/Entities/Entity.cs
  Intersect.Server.Core/Entities/Player.cs
Labels: bug

#2178 fix: item's quick cast
  Intersect.Server.Core/Entities/Player.cs
Labels: bug

#2186 fix: update map grid cache when editing maps
  Intersect.Server.Core/Maps/MapGrid.cs
Labels: bug

#2180 feature: ability to play sounds within the animation editor
  Intersect.Editor/Forms/Editors/frmAnimation.Designer.cs
  Intersect.Editor/Forms/Editors/frmAnimation.cs
  Intersect.Editor/Localization/Strings.cs
Labels: feature request

#2197 fix: show MapEditor upon starting the editor
  Intersect.Editor/Forms/frmMain.cs
Labels: bug
